# Generated by Django 2.2.10 on 2020-11-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('temperature', models.SmallIntegerField()),
                ('difference', models.CharField(max_length=128)),
            ],
        ),
    ]
